name: Publish build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and publish project
        run: |
              dotnet build hv-sos100-dataservice/Hv.Sos100.DataService.Log.Api.csproj -c Release

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: publish
          path: publish
